# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-31 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('df', models.CharField(max_length=100, verbose_name='磁盘分区')),
                ('os', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac')], max_length=30, verbose_name='系统平台')),
                ('note', models.GenericIPAddressField(verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
