# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='磁盘使用率')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
            ],
        ),
        migrations.CreateModel(
            name='HostCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='ip')),
                ('filesystem', models.CharField(max_length=64, verbose_name='filesystem')),
                ('size', models.CharField(max_length=64, verbose_name='size')),
                ('used', models.CharField(max_length=64, verbose_name='used')),
                ('used_percent', models.CharField(max_length=64, verbose_name='used_percent')),
                ('avail', models.CharField(max_length=64, verbose_name='avail')),
                ('mounted', models.CharField(max_length=64, verbose_name='mounted')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': '磁盘容量数据',
                'verbose_name_plural': '磁盘容量数据',
            },
        ),
        migrations.CreateModel(
            name='HostCapacityApiCheckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='ip')),
                ('mounted', models.CharField(max_length=64, verbose_name='mounted')),
                ('used_percent', models.CharField(max_length=64, verbose_name='used_percent')),
                ('check_time', models.DateTimeField(auto_now=True, verbose_name='check time')),
            ],
            options={
                'verbose_name': 'API磁盘容量查询记录',
                'verbose_name_plural': 'API磁盘容量查询记录',
            },
        ),
        migrations.CreateModel(
            name='Hostlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=30, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('df', models.CharField(max_length=100, verbose_name='磁盘分区')),
                ('os', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac')], max_length=30, verbose_name='系统平台')),
                ('note', models.GenericIPAddressField(verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
