# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-31 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='磁盘使用率')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
            ],
        ),
        migrations.RenameField(
            model_name='hostlist',
            old_name='name',
            new_name='host',
        ),
    ]
