# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='ip')),
                ('filesystem', models.CharField(max_length=64, verbose_name='filesystem')),
                ('size', models.CharField(max_length=64, verbose_name='size')),
                ('used', models.CharField(max_length=64, verbose_name='used')),
                ('used_percent', models.CharField(max_length=64, verbose_name='used_percent')),
                ('avail', models.CharField(max_length=64, verbose_name='avail')),
                ('mounted', models.CharField(max_length=64, verbose_name='mounted')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': '磁盘容量数据',
                'verbose_name_plural': '磁盘容量数据',
            },
        ),
    ]
